services:
  - type: web
    name: ecoplate-backend
    env: java
    buildCommand: ./mvnw package
    startCommand: java -jar target/ecoplate-0.0.1-SNAPSHOT.jar
    branch: main
    region: oregon
    plan: free